name: audit

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up uv
        uses: astral-sh/setup-uv@v6

      - name: Run audit script
        run: uv run scripts/audit.py
